import Image1 from '../../assets/personal-portfolio-template.png';
import Image2 from '../../assets/tc-template.png';
import Image3 from '../../assets/bbb-template.png';
// import Image4 from '../../assets/paul-hobbs-resume-rejuvenis-spajpg.jpg';
import Image5 from '../../assets/pb-template.png';

export const projects = [
  {
    id: 1,
    title: 'My Website',
    subtitle: 'HTML5, CSS3, React, SwiperJS, EmailJS',
    description:
      'Take a peek behind the scenes at the code that makes this website tick. It was built with HTML5, CSS3, and React, and features nested array mapping along with various states to manage front-end rendering.',
    image: Image1,
    link: 'https://github.com/paulwrivera/personalwebsite',
    tags: ['HTML5', 'CSS3', 'React'],
  },
  {
    id: 2,
    title: 'Paul Blogs',
    subtitle: 'Next.js, React, GraphQL, Tailwind CSS',
    description:
      'This open source blog pulls data from GraphCMS using GraphQL. It features posts written in Markdown, featured posts, related posts, categories, authors, user submitted comments, and a Tailwind styled layout.',
    image: Image5,
    link: 'https://graphql-nextjs-blog-pink.vercel.app/',
    tags: ['Next', 'React', 'GraphQL', 'Tailwind'],
  },
  {
    id: 3,
    title: 'Twitter Clone',
    subtitle: 'NodeJS, PassportJS, MongoDB, EJS',
    description:
      'My Twitter clone currently allows for the user registration, creating posts, liking and commenting, and also displays individual post pages. The feed is generated by mapping through posts stored in a Firebase database.',
    image: Image2,
    link: 'https://github.com/paulwrivera/twitter-clone',
    tags: ['Next', 'Next-Auth', 'Firebase', 'Tailwind'],
  },
  {
    id: 4,
    title: 'Blended Boston Blondes',
    subtitle: 'SquareSpace and SEO',
    description:
      'Jasmine is a high-end cosmetologist and needed a brand identity, color scheme, as well as a website for her clients. Utilizing SquareSpace, I designed a website that not only looks great but is incredibly easy to use.',
    image: Image3,
    link: 'https://www.blondeboston.com/',
    tags: ['Squarespace', 'SEO', 'Branding'],
  },
  // {
  //   id: 5,
  //   title: 'Rejuvenis Spa',
  //   subtitle: 'SquareSpace and SEO',
  //   description:
  //     'Maritza runs a high-end spa in Massachusetts and needed a beautiful website to support her business. Utilizing both standard and local SEO best practices I positioned Maritza ahead of her competition.',
  //   image: Image4,
  //   link: 'https://rejuvenisspa.com',
  //   tags: ['Squarespace', 'SEO', 'Branding'],
  // },
];
